requirements:
	pip install -r requirements.txt

quality:
	pycodestyle todoapp
	pylint todoapp


migrations:
	python manage.py makemigrations


migrate:
	python manage.py migrate


serve:
	python manage.py runserver 0.0.0.0:8000
